/// <reference types="cypress"/>
//require('cypress-mochawesome-reporter/plugin')(on);
import {faker } from '@faker-js/faker';
const password = faker.internet.password(12, false, /[a-zA-Z0-9\-\_\!\@\#\$\%\^\&\*\(\)]/);
const firstname = faker.person.firstName()
const lastname = faker.person.lastName()
const email = faker.internet.email()
describe('Test suite Magento', () => {
  it('should create an account', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > :nth-child(3) > a').click()
    cy.get('#firstname').type(firstname)
    cy.get('#lastname').type(lastname)
    cy.get('#email_address').type(email)
    cy.get('#password').type(password)
    cy.get('#password-confirmation').type(password)
    cy.log('toto'+password)
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.url().should('contain','customer/account')
    cy.get('.base').should('be.visible').and('have.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', firstname + ' ' +lastname+ '\n' + email)
    cy.screenshot('compte créé')
  })
    it('should sign in', () => {
      cy.visit('https://magento.softwaretestingboard.com/')
      cy.get('.panel > .header > .authorization-link > a').click()
      cy.get('#email').type(email)
      //cy.get('#email').type('michel2@gmail.com')
      cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type(password)
      //cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('Maurice258')
      cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2 > span').click()
      cy.get('#ui-id-8 > span').click()
      cy.get(':nth-child(6) > :nth-child(1) > a').click()
      cy.get(':nth-child(3) > .product-item-info > .details > .name > .product-item-link').click()
      cy.get('#product-addtocart-button').click()
      cy.get('.message-success > div').should('contain.text','You added Driven Backpack to your shopping cart')
      cy.get('.showcart').click()
      cy.get('#top-cart-btn-checkout').click()
      cy.get('[name="street[0]"]').type('rue de paris')
      cy.get('[name="city"]').type('paris')
      cy.get('[name="region_id"]').select('Arizona')
      cy.get('[name="postcode"]').type('75016')
      cy.get('[name="telephone"]').type('0123456789')
      //cy.get('[name="ko_unique_1"]').check()
      cy.get('[value=tablerate_bestway]').check()
      //cy.get('[value="flatrate_flatrate"]').check()
      cy.get('.button').click()
      cy.get('[class="action primary checkout"]').click()
      cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Thank you for your purchase!')
      cy.screenshot('paiement validé')
})
it('should not sign in', () => {
  cy.visit('https://magento.softwaretestingboard.com/')
  cy.get('.panel > .header > .authorization-link > a').click()
  cy.get('#email').type('michel2@gmail.com')
  cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('Mauridu')
  cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2 > span').click()
  cy.screenshot('compte non reconnu')
  })
})